# Generated by Django 5.0 on 2024-01-12 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_address_options_alter_cartorder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address'},
        ),
    ]
