# Generated by Django 5.0 on 2024-01-15 19:57

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='coverimage',
            field=models.ImageField(default='vendor.jpg', upload_to=core.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='core.vendor'),
        ),
    ]
