# Generated by Django 5.0 on 2024-01-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_vendor_coverimage_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_address',
            field=models.TextField(blank=True, default='Near khare mai mandir (485771)', null=True),
        ),
    ]
