# Generated by Django 5.0 on 2024-02-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_delivery_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtn', models.CharField(max_length=300, null=True)),
                ('ans', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
