# Generated by Django 5.0 on 2024-02-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_faqs_options_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tags',
            new_name='tagsss',
        ),
    ]
