# Generated by Django 5.0 on 2024-02-08 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_cartorder_razor_pay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.cartorder'),
            preserve_default=False,
        ),
    ]
