# Generated by Django 5.0 on 2024-02-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_cartorder_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
